var tableauQuestion = [
    {   question : "Kui sa sõidad 120 KM/H ning lähened asulale, siis peaksid sa:",
        propositionA : "Kiirendama",
        propositionB : "Hoidma kiirust",
        propositionC : "Langetama sõidukiirust",
        propositionD : "Sooritama äkkpidurduse",
        reponse : "C"},

    {   question : "Kui sa sooritad foori juures parempööred, kuid teed ületab jalakäija, siis sa:",
        propositionA : "Sõidad jalakäijast mööda",
        propositionB : "Kontrollid, et ühtegi teist sõidukit ümbruses ei oleks",
        propositionC : "Ootad kuni jalakäija on tee ületanud",
        propositionD : "Lased jälakaija maha ja sõidad edasi",
        reponse : "C"},

    {   question : "Linnasisene kiirusepiirang on: __ KM/H",
        propositionA : "30",
        propositionB : "120",
        propositionC : "50",
        propositionD : "70",
        reponse : "D"},

  {   question : "Enne igat reavahetust pead sa:",
        propositionA : "Kontrollima oma peeglivaadet",
        propositionB : "Kontrollima pimenurki",
        propositionC : "Suunatulega märku andma",
        propositionD : "Kõik ülaltoodud vastused",
        reponse : "D"},

  {   question : "Parklas liigeldes pead sa meeles pidama:",
        propositionA : "Oma telefoninumbrit",
        propositionB : "Oma pagasiruumi sisu",
        propositionC : "Kas sul jäi kodus külmkapp lahti",
        propositionD : "Paremakäe reeglit",
        reponse : "D"},

  {   question : "Mis olukorras võid sa fooriga ristmikku ületada?",
        propositionA : "Kui foor on roheline",
        propositionB : "Kui kedagi ei ole ristmikul",
        propositionC : "Kui sa oled maanteel",
        propositionD : "Kui foor on roheline ja/või sa sooritad parempööret",
        reponse : "D"},

  {   question : "Sa näed autot punase fooriga ristmiku suunas kihutamas, kuid sinul on roheline tuli. Sa:",
        propositionA : "Kiirendad, lootes teda rammida",
        propositionB : "Jälgid autot ja jääd vajadusel seisma, et vältida kokkupõrget",
        propositionC : "Kihutad talle järgi, et teda maha lasta",
        propositionD : "Sõidad rahulikult edasi, sest sul on tuli roheline",
        reponse : "B"},

  {   question : "Kiirteel on kiirusepiirang: __ KM/H",
        propositionA : "120",
        propositionB : "Kiirteel ei ole kiirusepiirangut",
        propositionC : "180",
        propositionD : "220",
        reponse : "B"},

  {   question : "Sa jõuad ristmikuni, kus sa tead, et asub STOP märk, kuid keegi on selle alla ajanud. Sa:",
        propositionA : "Käitud nagu märk oleks alles",
        propositionB : "Sõidad edasi",
        propositionC : "Jätad auto keset teed, et märki autosse vedada",
        propositionD : "Jääd ristmikule ootama, kuni märk tagasi paigaldatakse",
        reponse : "A"},

  {   question : "Kui keegi sooritab sulle möödasõitu, siis sa:",
        propositionA : "Rammid ta teelt välja",
        propositionB : "Kiirendad",
        propositionC : "Hoidud tee paremale ning vajadusel langetad kiirust",
        propositionD : "Alustad möödasõitu",
        reponse : "C"},
]
