Config = Config or {}

Config.RosterLink = {
    ['police'] = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRJg2Jl6D9vW4D8SW2s6G1tunypOeUA-bORx6IMf2TTVPKsxYZ06HhTwiygfv-9FDvTH-mKJaV3i8dp/pubhtml?widget=true&amp;headers=false',
    ['ambulance'] = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQGFxDXRD_4-YoMKEbWZVkIi5I7qbzuby3Sw2R14yi6VOtMmhnVsBcM6WaeXgCC44TZjqu1WlmMsBSq/pubhtml?widget=true&amp;headers=false',
    ['doj'] = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR7B313K3_zkUwzQtl_5pPrcd52GnC_DImf_5-sruZBF7XkXpCzk0k7EoNoQmxWaSLTxo2P9kCcVO2P/pubhtml?widget=true&amp;headers=false',
}

Config.OnlyShowOnDuty = true

Config.Fuel = "LegacyFuel" -- "LegacyFuel", "lj-fuel"

Config.PenalCodeTitles = {
    [1] = 'SÜÜTEOD ISIKU VASTU',
    [2] = 'SÜÜTEOD SEOTUD VARGUSEGA',
    [3] = 'SÜÜTEOD SEOTUD PETTUSEGA',
    [4] = 'SÜÜTEOD SEOTUD VARA KAHJUSTAMISEGA',
    [5] = 'SÜÜTEOD AVALIKU HALDUSE VASTU',
    [6] = 'SÜÜTEOD AVALIKU KORRA VASTU',
    [7] = 'SÜÜTEOD TERVISE JA MORAALIDE VASTU',
    [8] = 'SÜÜTEOD AVALIKU TURVALISUSE VASTU',
    [9] = 'SÜÜTEOD SEOTUD SÕIDUKI KÄITLEMISEGA',
    [10] = 'SÜÜTEOD SEOTUD ELUSLOODUSE HEAOLUGA',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Kerge Ründamine', class = 'Väärtegu', id = 'P.C. 1001', months = 7, fine = 100, color = 'green'},
        [2] = {title = 'Ründamine', class = 'Väärtegu', id = 'P.C. 1002', months = 15, fine = 250, color = 'orange'},
        [3] = {title = 'Süvenenud Ründamine', class = 'Kuritegu', id = 'P.C. 1003', months = 20, fine = 500, color = 'orange'},
        [4] = {title = 'Ründamine Surmava Relvaga', class = 'Kuritegu', id = 'P.C. 1004', months = 30, fine = 1500, color = 'red'},
        [5] = {title = 'Tahtmatu Tapmine', class = 'Kuritegu', id = 'P.C. 1005', months = 60, fine = 2500, color = 'red'},
        [6] = {title = 'Sõidukiga Tapmine', class = 'Kuritegu', id = 'P.C. 1006', months = 75, fine = 5000, color = 'red'},
        [7] = {title = 'Tsiviilisiku Mõrvakatse', class = 'Kuritegu', id = 'P.C. 1007', months = 50, fine = 4000, color = 'red'},
        [8] = {title = 'Teise Astme Mõrv', class = 'Kuritegu', id = 'P.C. 1008', months = 100, fine = 6000, color = 'red'},
        [9] = {title = 'Teise Astme Mõrva Kaasosaline', class = 'Kuritegu', id = 'P.C. 1009', months = 50, fine = 4500, color = 'red'},
        [10] = {title = 'Esimese Astme Mõrv', class = 'Kuritegu', id = 'P.C. 1010', months = 120, fine = 10000, color = 'red'},
        [11] = {title = 'Esimese Astme Mõrva Kaasosaline', class = 'Kuritegu', id = 'P.C. 1011', months = 60, fine = 5500, color = 'red'},
        [12] = {title = 'Riigitöötaja Mõrv', class = 'Kuritegu', id = 'P.C. 1012', months = 20, fine = 6000, color = 'red'},
        [13] = {title = 'Riigitöötaja Mõrvakatse', class = 'Kuritegu', id = 'P.C. 1013', months = 10, fine = 5000, color = 'red'},
        [14] = {title = 'Riigitöötaja Mõrva/Mõrvakatse Kaasosaline', class = 'Kuritegu', id = 'P.C. 1014', months = 10, fine = 4500, color = 'red'},
        [15] = {title = 'Ebaseaduslik Vangistus', class = 'Väärtegu', id = 'P.C. 1015', months = 10, fine = 5000, color = 'green'},
        [16] = {title = 'Inimrööv', class = 'Kuritegu', id = 'P.C. 1016', months = 15, fine = 2000, color = 'orange'},
        [17] = {title = 'Inimröövi Kaasosaline', class = 'Kuritegu', id = 'P.C. 1017', months = 7, fine = 1200, color = 'orange'},
        [18] = {title = 'Inimröövi Katse', class = 'Kuritegu', id = 'P.C. 1018', months = 10, fine = 1500, color = 'orange'},
        [19] = {title = 'Pantvangi Võtmine', class = 'Kuritegu', id = 'P.C. 1019', months = 20, fine = 1200, color = 'orange'},
        [20] = {title = 'Pantvangi Võtmises Kaasosaline', class = 'Kuritegu', id = 'P.C. 1020', months = 10, fine = 800, color = 'orange'},
        [21] = {title = 'Riigitöötaja Ebaseaduslik Vangistus', class = 'Kuritegu', id = 'P.C. 1021', months = 25, fine = 5500, color = 'orange'},
        [22] = {title = 'Kuritegevlikud Ähvardused', class = 'Väärtegu', id = 'P.C. 1022', months = 5, fine = 1300, color = 'orange'},
        [23] = {title = 'Hoolimatu Ohustamine', class = 'Väärtegu', id = 'P.C. 1023', months = 10, fine = 750, color = 'orange'},
        [24] = {title = 'Grupeeringuga Seotud Tulistamine', class = 'Kuritegu', id = 'P.C. 1024', months = 30, fine = 2500, color = 'red'},
        [25] = {title = 'Kannibalism', class = 'Kuritegu', id = 'P.C. 1025', months = 60, fine = 0, color = 'red'},
        [26] = {title = 'Piinamine', class = 'Kuritegu', id = 'P.C. 1026', months = 40, fine = 3000, color = 'red'},
    },
    [2] = {
        [1] = {title = 'Pisivargus', class = 'Rikkumine', id = 'P.C. 2001', months = 0, fine = 250, color = 'green'},
        [2] = {title = 'Vargus', class = 'Väärtegu', id = 'P.C. 2002', months = 10, fine = 600, color = 'green'},
        [3] = {title = 'Autovargus', class = 'Kuritegu', id = 'P.C. 2003', months = 15, fine = 900, color = 'green'},
        [4] = {title = 'Autode Röövimine', class = 'Kuritegu', id = 'P.C. 2005', months = 30, fine = 2000, color = 'orange'},
        [5] = {title = 'Sissemurdmine', class = 'Väärtegu', id = 'P.C. 2006', months = 10, fine = 500, color = 'green'},
        [6] = {title = 'Röövimine', class = 'Kuritegu', id = 'P.C. 2007', months = 25, fine = 2000, color = 'green'},
        [7] = {title = 'Röövimisel Kaasosaline', class = 'Kuritegu', id = 'P.C. 2008', months = 12, fine = 1000, color = 'green'},
        [8] = {title = 'Röövimise Katse', class = 'Kuritegu', id = 'P.C. 2009', months = 20, fine = 1300, color = 'green'},
        [9] = {title = 'Relvastatud Röövimine', class = 'Kuritegu', id = 'P.C. 2010', months = 30, fine = 3000, color = 'orange'},
        [10] = {title = 'Relvastatud Röövimisel Kaasosaline', class = 'Kuritegu', id = 'P.C. 2011', months = 15, fine = 1500, color = 'orange'},
        [11] = {title = 'Relvastatud Röövimise Katse', class = 'Kuritegu', id = 'P.C. 2012', months = 25, fine = 1700, color = 'orange'},
        [12] = {title = 'Vargused', class = 'Kuritegu', id = 'P.C. 2013', months = 45, fine = 4000, color = 'orange'},
        [13] = {title = 'Maksmata Lahkumine', class = 'Rikkumine', id = 'P.C. 2014', months = 0, fine = 800, color = 'green'},
        [14] = {title = 'Ebaseadusliku Valuuta Omamine', class = 'Väärtegu', id = 'P.C. 2015', months = 10, fine = 750, color = 'green'},
        [15] = {title = 'Riigi Poolt Väljastatud Varustuse Omamine', class = 'Väärtegu', id = 'P.C. 2016', months = 15, fine = 1000, color = 'green'},
        [16] = {title = 'Kuriteos Kasutatud Esemete Omamine', class = 'Väärtegu', id = 'P.C. 2017', months = 10, fine = 900, color = 'green'},
        [17] = {title = 'Kuriteos Kasutatud Esemete Müük', class = 'Kuritegu', id = 'P.C. 2018', months = 15, fine = 1400, color = 'orange'},
        [18] = {title = 'Lennumasina Vargus', class = 'Kuritegu', id = 'P.C. 2019', months = 20, fine = 1200, color = 'green'},
    },
    [3] = {
        [1] = {title = 'Identiteedivargus', class = 'Väärtegu', id = 'P.C. 3001', months = 15, fine = 1250, color = 'green'},
        [2] = {title = 'Riigitöötaja Identiteedivargus', class = 'Kuritegu', id = 'P.C. 3002', months = 25, fine = 2250, color = 'green'},
        [3] = {title = 'Kohtuniku Identiteedivargus', class = 'Kuritegu', id = 'P.C. 3003', months = 30, fine = 2500, color = 'green'},
        [4] = {title = 'Varastatud Dokumendi Omamine', class = 'Väärtegu', id = 'P.C. 3004', months = 10, fine = 1000, color = 'green'},
        [5] = {title = 'Varastatud Riigitöötaja Dokumendi Omamine', class = 'Väärtegu', id = 'P.C. 3005', months = 20, fine = 1500, color = 'green'},
        [6] = {title = 'Väljapressimine', class = 'Kuritegu', id = 'P.C. 3006', months = 20, fine = 1200, color = 'orange'},
        [7] = {title = 'Pettus', class = 'Väärtegu', id = 'P.C. 3007', months = 10, fine = 500, color = 'green'},
        [8] = {title = 'Võltsimine', class = 'Väärtegu', id = 'P.C. 3008', months = 15, fine = 750, color = 'green'},
        [9] = {title = 'Rahapesu', class = 'Kuritegu', id = 'P.C. 3009', months = 0, fine = 1000, color = 'red'},
    },
    [4] = {
        [1] = {title = 'Sissetungimine', class = 'Väärtegu', id = 'P.C. 4001', months = 10, fine = 500, color = 'green'},
        [2] = {title = 'Kuritegevlik Sissemurdmine', class = 'Kuritegu', id = 'P.C. 4002', months = 15, fine = 1500, color = 'green'},
        [3] = {title = 'Süütamine', class = 'Kuritegu', id = 'P.C. 4003', months = 15, fine = 1500, color = 'orange'},
        [4] = {title = 'Vara Kahjustamine', class = 'Rikkumine', id = 'P.C. 4004', months = 0, fine = 300, color = 'green'},
        [5] = {title = 'Riigi Vara Kahjustamine', class = 'Kuritegu', id = 'P.C. 4005', months = 20, fine = 800, color = 'green'},
        [6] = {title = 'Risustamine', class = 'Rikkumine', id = 'P.C. 4006', months = 0, fine = 200, color = 'green'},
    },
    [5] = {
        [1] = {title = 'Altkäemaks Riigitöötajale', class = 'Kuritegu', id = 'P.C. 5001', months = 20, fine = 3500, color = 'green'},
        [2] = {title = 'Maskiseaduse Rikkumine', class = 'Rikkumine', id = 'P.C. 5002', months = 0, fine = 750, color = 'green'},
        [3] = {title = 'Salakaubavedu Riigiasutuses', class = 'Kuritegu', id = 'P.C. 5003', months = 25, fine = 1000, color = 'green'},
        [4] = {title = 'Varastatud Esemete Omamine', class = 'Väärtegu', id = 'P.C. 5004', months = 10, fine = 500, color = 'green'},
        [5] = {title = 'Põgenemine', class = 'Kuritegu', id = 'P.C. 5005', months = 10, fine = 450, color = 'green'},
        [6] = {title = 'Vanglast Põgenemine', class = 'Kuritegu', id = 'P.C. 5006', months = 30, fine = 2500, color = 'orange'},
        [7] = {title = 'Vanglast Põgenemisel Kaasosaline', class = 'Kuritegu', id = 'P.C. 5007', months = 25, fine = 2000, color = 'orange'},
        [8] = {title = 'Vanglast Põgenemise Katse', class = 'Kuritegu', id = 'P.C. 5008', months = 20, fine = 1500, color = 'orange'},
        [9] = {title = 'Valevande Andmine', class = 'Kuritegu', id = 'P.C. 5009', months = 0, fine = 1000, color = 'green'},
        [10] = {title = 'Lähenemiskeelu Rikkumine', class = 'Kuritegu', id = 'P.C. 5010', months = 20, fine = 2000, color = 'green'},
        [11] = {title = 'Omastamine', class = 'Kuritegu', id = 'P.C. 5011', months = 45, fine = 10000, color = 'green'},
        [12] = {title = 'Ebaseaduslik Tegevus', class = 'Kuritegu', id = 'P.C. 5012', months = 15, fine = 1500, color = 'orange'},
        [13] = {title = 'Hädaabi Süsteemide Väärkasutus', class = 'Rikkumine', id = 'P.C. 5013', months = 0, fine = 600, color = 'orange'},
        [14] = {title = 'Vandenõu', class = 'Väärtegu', id = 'P.C. 5014', months = 10, fine = 500, color = 'green'},
        [15] = {title = 'Kohtumääruse Rikkumine', class = 'Väärtegu', id = 'P.C. 5015', months = 0, fine = 750, color = 'orange'},
        [16] = {title = 'Kohtusse Mitteilmumine', class = 'Väärtegu', id = 'P.C. 5016', months = 0, fine = 500, color = 'orange'},
        [17] = {title = 'Kohtupõlgus', class = 'Kuritegu', id = 'P.C. 5017', months = 0, fine = 1000, color = 'orange'},
        [18] = {title = 'Arreteermisel Vastupanu Esitamine', class = 'Väärtegu', id = 'P.C. 5018', months = 5, fine = 400, color = 'orange'},
    },
    [6] = {
        [1] = {title = 'Politseiniku Käsu Eiramine', class = 'Rikkumine', id = 'P.C. 6001', months = 0, fine = 750, color = 'green'},
        [2] = {title = 'Korrarikkumine', class = 'Rikkumine', id = 'P.C. 6002', months = 0, fine = 250, color = 'green'},
        [3] = {title = 'Rahu Segamine', class = 'Rikkumine', id = 'P.C. 6003', months = 0, fine = 350, color = 'green'},
        [4] = {title = 'Valeteate Tegemine', class = 'Väärtegu', id = 'P.C. 6004', months = 10, fine = 750, color = 'green'},
        [5] = {title = 'Ahistamine', class = 'Väärtegu', id = 'P.C. 6005', months = 10, fine = 500, color = 'orange'},
        [6] = {title = 'Õigusemõistmise Takistamine', class = 'Väärtegu', id = 'P.C. 6006', months = 10, fine = 500, color = 'green'},
        [7] = {title = 'Mässu Õhutamine', class = 'Kuritegu', id = 'P.C. 6007', months = 25, fine = 1000, color = 'orange'},
        [8] = {title = 'Riigiasutuse Alal Looderdamine', class = 'Rikkumine', id = 'P.C. 6008', months = 0, fine = 500, color = 'green'},
        [9] = {title = 'Rikkumine', class = 'Väärtegu', id = 'P.C. 6009', months = 10, fine = 500, color = 'green'},
        [10] = {title = 'Sõiduki Rikkumine', class = 'Väärtegu', id = 'P.C. 6010', months = 15, fine = 750, color = 'green'},
        [11] = {title = 'Asitõendite Võltsimine', class = 'Kuritegu', id = 'P.C. 6011', months = 20, fine = 1000, color = 'green'},
        [12] = {title = 'Tunnistaja Võltsimine', class = 'Kuritegu', id = 'P.C. 6012', months = 0, fine = 1000, color = 'green'},
        [13] = {title = 'Dokumendi Mitteesitamine', class = 'Väärtegu', id = 'P.C. 6013', months = 15, fine = 500, color = 'green'},
        [14] = {title = 'Seaduse Pealesurumine Ilma Loata', class = 'Kuritegu', id = 'P.C. 6014', months = 30, fine = 1500, color = 'orange'},
        [15] = {title = 'Ebaseaduslik Meisterdamine', class = 'Väärtegu', id = 'P.C. 6015', months = 10, fine = 750, color = 'orange'},
        [16] = {title = 'Korruptsioon', class = 'Kuritegu', id = 'P.C. 6016', months = 0, fine = 0, color = 'red'},
        [17] = {title = 'Jälitamine', class = 'Kuritegu', id = 'P.C. 6017', months = 40, fine = 1500, color = 'orange'},
        [18] = {title = 'Kuriteos Kaasaaitamine', class = 'Väärtegu', id = 'P.C. 6018', months = 15, fine = 450, color = 'orange'},
        [19] = {title = 'Tagaotsitava Isiku Varjamine', class = 'Väärtegu', id = 'P.C. 6019', months = 10, fine = 1000, color = 'green'},
    },
    [7] = {
        [1] = {title = 'Marijuana Omamine', class = 'Kuritegu', id = 'P.C. 7001', months = 15, fine = 1000, color = 'green'},
        [2] = {title = 'Marijuana Kasvatamine', class = 'Kuritegu', id = 'P.C. 7002', months = 30, fine = 1500, color = 'orange'},
        [3] = {title = 'Marijuana Omamine Müügi Kavatsusega', class = 'Kuritegu', id = 'P.C. 7003', months = 30, fine = 3000, color = 'orange'},
        [4] = {title = 'Kokaiini Omamine', class = 'Kuritegu', id = 'P.C. 7004', months = 25, fine = 1500, color = 'green'},
        [5] = {title = 'Kokaiini Omamine Müügi Kavatsusega', class = 'Kuritegu', id = 'P.C. 7005', months = 35, fine = 4500, color = 'orange'},
        [6] = {title = 'Metamfetamiini Omamine', class = 'Kuritegu', id = 'P.C. 7006', months = 25, fine = 1500, color = 'green'},
        [7] = {title = 'Metamfetamiini Omamine Müügi Kavatsusega', class = 'Kuritegu', id = 'P.C. 7007', months = 35, fine = 4500, color = 'orange'},
        [8] = {title = 'Oxy Omamine', class = 'Kuritegu', id = 'P.C. 7008', months = 25, fine = 1500, color = 'green'},
        [9] = {title = 'Oxy Omamine Müügi Kavatsusega', class = 'Kuritegu', id = 'P.C. 7009', months = 35, fine = 4500, color = 'orange'},
        [10] = {title = 'Heroiini Omamine', class = 'Kuritegu', id = 'P.C. 7010', months = 25, fine = 1500, color = 'green'},
        [11] = {title = 'Heroiini Omamine Müügi Kavatsusega', class = 'Kuritegu', id = 'P.C. 7011', months = 35, fine = 4500, color = 'orange'},
        [12] = {title = 'Narkootilise Aine Müük', class = 'Väärtegu', id = 'P.C. 7012', months = 10, fine = 1000, color = 'green'},
        [13] = {title = 'Narkootikumite Hulgimüük', class = 'Kuritegu', id = 'P.C. 7013', months = 60, fine = 6000, color = 'red'},
        [14] = {title = 'Laiba Rüvetamine', class = 'Kuritegu', id = 'P.C. 7014', months = 20, fine = 1500, color = 'orange'},
        [15] = {title = 'Avalik Joomine', class = 'Rikkumine', id = 'P.C. 7015', months = 0, fine = 500, color = 'green'},
        [16] = {title = 'Enesepaljastamine', class = 'Väärtegu', id = 'P.C. 7016', months = 10, fine = 750, color = 'green'},
    },
    [8] = {
        [1] = {title = 'Ebaseadusliku Relva Omamine (TASE 1)', class = 'Kuritegu', id = 'P.C. 8001', months = 10, fine = 500, color = 'green'},
        [2] = {title = 'Ebaseadusliku Relva Omamine (TASE 2)', class = 'Kuritegu', id = 'P.C. 8002', months = 15, fine = 2000, color = 'green'},
        [3] = {title = 'Ebaseadusliku Relva Omamine (TASE 3)', class = 'Kuritegu', id = 'P.C. 8003', months = 30, fine = 5500, color = 'green'},
        [4] = {title = 'Ebaseaduslik Relva Müük (TASE 1)', class = 'Kuritegu', id = 'P.C. 8004', months = 15, fine = 2000, color = 'orange'},
        [5] = {title = 'Ebaseaduslik Relva Müük (TASE 2)', class = 'Kuritegu', id = 'P.C. 8005', months = 20, fine = 4000, color = 'orange'},
        [6] = {title = 'Ebaseaduslik Relva Müük (TASE 3)', class = 'Kuritegu', id = 'P.C. 8006', months = 35, fine = 10000, color = 'orange'},
        [7] = {title = 'Ebaseaduslik Relva Kasutamine', class = 'Väärtegu', id = 'P.C. 8007', months = 10, fine = 1450, color = 'orange'},
        [8] = {title = 'Ebaseadusliku Relvalisa Omamine', class = 'Väärtegu', id = 'P.C. 8008', months = 10, fine = 1000, color = 'green'},
        [9] = {title = 'Relvade Hulgimüük', class = 'Kuritegu', id = 'P.C. 8009', months = 60, fine = 12000, color = 'red'},
        [10] = {title = 'Relvaga Vehkimine', class = 'Väärtegu', id = 'P.C. 8010', months = 15, fine = 700, color = 'orange'},
        [11] = {title = 'Ülestõus', class = 'Kuritegu', id = 'P.C. 8011', months = 0, fine = 1000, color = 'red'},
        [12] = {title = 'Keelualasse Lendamine', class = 'Kuritegu', id = 'P.C. 8012', months = 20, fine = 1500, color = 'green'},
        [13] = {title = 'Valest Kohast Tee Ületamine', class = 'Rikkumine', id = 'P.C. 8013', months = 0, fine = 150, color = 'green'},
        [14] = {title = 'Ebaseaduslike Lõhkeainete Kasutamine', class = 'Kuritegu', id = 'P.C. 8014', months = 30, fine = 2500, color = 'orange'},
    },
    [9] = {
        [1] = {title = 'Joobes Seisundis Sõiduki Juhtimine', class = 'Väärtegu', id = 'P.C. 9001', months = 5, fine = 300, color = 'green'},
        [2] = {title = 'Mittepeatumine', class = 'Väärtegu', id = 'P.C. 9002', months = 5, fine = 500, color = 'green'},
        [3] = {title = 'Hooletu Mittepeatumine', class = 'Kuritegu', id = 'P.C. 9003', months = 10, fine = 800, color = 'orange'},
        [4] = {title = 'Alarmsõidukile Tee Mitte Andmine', class = 'Rikkumine', id = 'P.C. 9004', months = 0, fine = 600, color = 'green'},
        [5] = {title = 'Punase Foori Ületamine', class = 'Rikkumine', id = 'P.C. 9005', months = 0, fine = 250, color = 'green'},
        [6] = {title = 'Mittefunktionaalse Sõiduki Juhtimine', class = 'Rikkumine', id = 'P.C. 9006', months = 0, fine = 175, color = 'green'},
        [7] = {title = 'Lohakas Juhtimine', class = 'Rikkumine', id = 'P.C. 9007', months = 0, fine = 300, color = 'green'},
        [8] = {title = 'Hooletu Juhtimine', class = 'Väärtegu', id = 'P.C. 9008', months = 10, fine = 750, color = 'orange'},
        [9] = {title = 'Kiiruse Ületamine (TASE 1)', class = 'Rikkumine', id = 'P.C. 9009', months = 0, fine = 325, color = 'green'},
        [10] = {title = 'Kiiruse Ületamine (TASE 2)', class = 'Rikkumine', id = 'P.C. 9010', months = 0, fine = 650, color = 'green'},
        [11] = {title = 'Kiiruse Ületamine (TASE 3)', class = 'Rikkumine', id = 'P.C. 9011', months = 0, fine = 950, color = 'green'},
        [12] = {title = 'Ilma Lubadeta Juhtimine', class = 'Rikkumine', id = 'P.C. 9012', months = 0, fine = 500, color = 'green'},
        [13] = {title = 'Ebaseaduslik U-Pööre', class = 'Rikkumine', id = 'P.C. 9013', months = 0, fine = 200, color = 'green'},
        [14] = {title = 'Ebaseaduslik Möödasõit', class = 'Rikkumine', id = 'P.C. 9014', months = 0, fine = 300, color = 'green'},
        [15] = {title = 'Reas Mittepüsimine', class = 'Rikkumine', id = 'P.C. 9015', months = 0, fine = 300, color = 'green'},
        [16] = {title = 'Ebaseaduslik Pööre', class = 'Rikkumine', id = 'P.C. 9016', months = 0, fine = 150, color = 'green'},
        [17] = {title = 'Peatumisest Keeldumine', class = 'Rikkumine', id = 'P.C. 9017', months = 0, fine = 600, color = 'green'},
        [18] = {title = 'Ebaseaduslik Parkimine', class = 'Rikkumine', id = 'P.C. 9018', months = 0, fine = 300, color = 'green'},
        [19] = {title = 'Sündmuskohalt Põgenemine', class = 'Väärtegu', id = 'P.C. 9019', months = 10, fine = 500, color = 'green'},
        [20] = {title = 'Tuledeta Sõitmine', class = 'Rikkumine', id = 'P.C. 9020', months = 0, fine = 300, color = 'green'},
        [21] = {title = 'Street Race', class = 'Kuritegu', id = 'P.C. 9021', months = 20, fine = 1500, color = 'green'},
        [22] = {title = 'Ilma Loata Lennumasina Juhtimine', class = 'Kuritegu', id = 'P.C. 9022', months = 20, fine = 1500, color = 'orange'},
        [23] = {title = 'Ebaseaduslik Mootorsõiduki Kasutamine', class = 'Väärtegu', id = 'P.C. 9023', months = 10, fine = 750, color = 'green'},
    },
    [10] = {
        [1] = {title = 'Keelualas Jahipidamine', class = 'Rikkumine', id = 'P.C. 10001', months = 0, fine = 450, color = 'green'},
        [2] = {title = 'Ilma Loata Jahipidamine', class = 'Rikkumine', id = 'P.C. 10002', months = 0, fine = 450, color = 'green'},
        [3] = {title = 'Julmus Loomade Vastu', class = 'Väärtegu', id = 'P.C. 10003', months = 10, fine = 450, color = 'green'},
        [4] = {title = 'Jahipidamine Vale Relvaga', class = 'Väärtegu', id = 'P.C. 10004', months = 10, fine = 750, color = 'green'},
        [5] = {title = 'Üleküttimine', class = 'Väärtegu', id = 'P.C. 10005', months = 10, fine = 1000, color = 'green'},
        [6] = {title = 'Salaküttimine', class = 'Kuritegu', id = 'P.C. 10006', months = 20, fine = 1250, color = 'red'},
    }
}

Config.PoliceJobs = {
    ['police'] = true,
    ['bcso'] = false,
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = false,
}

Config.DojJobs = {
    ['lawyer'] = true,
    ['judge'] = true,
    ['senate'] = true,
}

-- Leave my hacky code alone ya goblins
Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end
-- Leave my hacky code alone ya goblins

Config.LogPerms = {
	['ambulance'] = {
		[5] = true,
	},
	['police'] = {
        [7] = true,
        [8] = true,
		[9] = true,
	},
    ['judge'] = {
        [1] = true,
	},
    ['senate'] = {
        [0] = true,
	},
}

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end

-- this is a hack, because the qb-menu in qb-policejob populates an impound location and passed it through to the event.
-- if this impound locations are changed in qb-policejob, they must also be changed here.
Config.ImpoundLocations = { 
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}