Config = Config or {}
Config.BillingCommissions = { -- This is a percentage (0.10) == 10%
    mechanic = 0.10,
    taxi = 0.75
}
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.OpenPhone = 244
Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "linear-gradient(0deg, rgba(4,103,0,1) 0%, rgba(6,131,0,1) 50%, rgba(8,180,0,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fa fa-phone-alt",
        tooltipText = "Telefon",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "linear-gradient(0deg, rgba(6,135,0,1) 0%, rgba(8,184,0,1) 50%, rgba(10,224,0,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-comment",
        tooltipText = "Messenger",
        tooltipPos = "top",
        style = "font-size: 2.8vh";
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "linear-gradient(0deg, rgba(11,13,17,1) 0%, rgba(21,25,31,1) 50%, rgba(34,40,49,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fa fa-cogs",
        tooltipText = "Seaded",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["twitter"] = {
        app = "twitter",
        color = "linear-gradient(0deg, rgba(0,107,161,1) 0%, rgba(0,154,221,1) 50%, rgba(0,183,255,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fab fa-twitter",
        tooltipText = "Twitter",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ["garage"] = {
        app = "garage",
        color = "linear-gradient(0deg, rgba(0,43,94,1) 0%, rgba(9,54,121,1) 50%, rgba(0,108,180,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-car",
        tooltipText = "Sõidukid",
        job = false,
        blockedjobs = {},
        slot = 19,
        Alerts = 0,
    },
    ["mail"] = {
        app = "mail",
        color = "linear-gradient(0deg, rgba(119,0,0,1) 0%, rgba(154,0,0,1) 50%, rgba(218,1,1,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-envelope-open-text",
        tooltipText = "Mail",
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ["advert"] = {
        app = "advert",
        color = "linear-gradient(0deg, rgba(147,73,0,1) 0%, rgba(190,90,0,1) 50%, rgba(255,126,0,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-bullhorn",
        tooltipText = "Kuulutused",
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ["bank"] = {
        app = "bank",
        color = "linear-gradient(0deg, rgba(0,120,59,1) 0%, rgba(0,168,83,1) 50%, rgba(0,215,102,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-money-check-alt",
        tooltipText = "Pank",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    ["crypto"] = {
        app = "crypto",
        color = "linear-gradient(0deg, rgba(40,40,40,1) 0%, rgba(91,91,91,1) 50%, rgba(140,140,140,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-coins",
        tooltipText = "Crypto",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ["racing"] = {
        app = "racing",
        color = "linear-gradient(0deg, rgba(85,0,0,1) 0%, rgba(110,0,0,1) 50%, rgba(142,0,0,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-flag-checkered",
        tooltipText = "Racing",
        job = false,
        blockedjobs = {},
        slot = 20,
        Alerts = 0,
    },
    -- ["houses"] = {
    --     app = "houses",
    --     color = "linear-gradient(0deg, rgba(166,149,0,1) 0%, rgba(200,183,0,1) 50%, rgba(255,233,0,1) 100%)",
    --     shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
    --     icon = "fas fa-home",
    --     tooltipText = "Kinnisvara",
    --     job = false,
    --     blockedjobs = {},
    --     slot = 10,
    --     Alerts = 0,
    -- },
    -- ["meos"] = {
    --     app = "meos",
    --     color = "#222831",
    --     icon = "fas fa-ad",
    --     tooltipText = "MDT",
    --     job = "police",
    --     blockedjobs = {},
    --     slot = 18,
    --     Alerts = 0,
    -- },
    ["lawyers"] = {
        app = "lawyers",
        color = "linear-gradient(0deg, rgba(113,2,22,1) 0%, rgba(156,2,30,1) 50%, rgba(220,20,56,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-briefcase",
        tooltipText = "Teenused",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    },
    ["gallery"] = {
        app = "gallery",
        color = "linear-gradient(0deg, rgba(19,23,28,1) 0%, rgba(34,40,49,1) 50%, rgba(66,78,96,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-images",
        tooltipText = "Galerii",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ["camera"] = {
        app = "camera",
        color = "linear-gradient(0deg, rgba(19,23,28,1) 0%, rgba(34,40,49,1) 50%, rgba(66,78,96,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-camera",
        tooltipText = "Kaamera",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ["solk"] = {
        app = "solk",
        color = "linear-gradient(0deg, rgba(166,14,46,1) 0%, rgba(220,20,60,1) 50%, rgba(255,24,74,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-pepper-hot",
        tooltipText = "Solk",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    ["fines"] = {
        app = "fines",
        color = "linear-gradient(0deg, rgba(74,86,120,1) 0%, rgba(102,119,168,1) 50%, rgba(131,154,222,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-file-invoice-dollar",
        tooltipText = "Trahvid",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 16,
        Alerts = 0,
    },
    ["jobs"] = {
        app = "jobs",
        color = "linear-gradient(0deg, rgba(19,111,89,1) 0%, rgba(26,167,135,1) 50%, rgba(37,219,175,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-clipboard-list",
        tooltipText = "Töökohad",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 17,
        Alerts = 0,
    },
    ["calculator"] = {
        app = "calculator",
        color = "linear-gradient(0deg, rgba(74,79,89,1) 0%, rgba(118,127,143,1) 50%, rgba(147,158,179,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-calculator",
        tooltipText = "Kalkulaator",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 18,
        Alerts = 0,
    },
    ["details"] = {
        app = "details",
        color = "linear-gradient(0deg, rgba(12,64,101,1) 0%, rgba(20,94,145,1) 50%, rgba(29,134,208,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-info",
        tooltipText = "Detailid",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ["employment"] = {
        app = "employment",
        color = "linear-gradient(0deg, rgba(55,12,92,1) 0%, rgba(91,19,150,1) 50%, rgba(116,25,191,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-users",
        tooltipText = "Grupid",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    },
    ["documents"] = {
        app = "documents",
        color = "linear-gradient(0deg, rgba(166,149,0,1) 0%, rgba(200,183,0,1) 50%, rgba(255,233,0,1) 100%)",
        shadow = "inset 0px 0px 10px 0px rgb(0 0 0 / 13%)",
        icon = "fas fa-notes-medical",
        tooltipText = "Notes",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
}

Config.MaxSlots = 24

Config.StoreApps = {
    ["territory"] = {
        app = "territory",
        color = "#353b48",
        icon = "fas fa-globe-europe",
        tooltipText = "Territorium",
        tooltipPos = "right",
        style = "";
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
        password = true,
        creator = "QBCore",
        title = "Territory",
    },
}
