Config = Config or {}

Config.MinimumPolice = 2

local waitTimeLower = (60 * 1000) * 17
local waitTimeHigher = (60 * 1000) * 45

Config.ContractWaitTime = math.random(waitTimeLower, waitTimeHigher)

Config.Vehicles = {
  -- D CLASS
  [1] = {
    -- D
    [1] = {vehicle = 'asea', label = 'Asea'},
    [2] = {vehicle = 'bifta', label = 'Bifta'},
    [3] = {vehicle = 'bison', label = 'Bison'},
    [4] = {vehicle = 'blista', label = 'Blista'},
    [5] = {vehicle = 'btype', label = 'Roosevelt'},
    [6] = {vehicle = 'burrito3', label = 'Burrito'},
    [7] = {vehicle = 'emperor', label = 'Emperor'},
    [8] = {vehicle = 'fagaloa', label = 'Fagaloa'},
    [9] = {vehicle = 'glendale', label = 'Glendale'},
    [10] = {vehicle = 'issi3', label = 'Issi Classic'},
    [11] = {vehicle = 'landstalker', label = 'Landstalker'},
    [12] = {vehicle = 'panto', label = 'Panto'},
    [13] = {vehicle = 'patriot', label = 'Patriot'},
    [14] = {vehicle = 'pigalle', label = 'Pigalle'},
    [15] = {vehicle = 'radi', label = 'Radius'},
    [16] = {vehicle = 'regina', label = 'Regina'},
    [17] = {vehicle = 'rhapsody', label = 'Rhapsody'},
    [18] = {vehicle = 'stalion', label = 'Stallion'},
    [19] = {vehicle = 'surge', label = 'Surge'},
    [20] = {vehicle = 'voodoo', label = 'Voodoo'},
    [21] = {vehicle = 'washington', label = 'Washington'},
    [22] = {vehicle = 'asbo', label = 'Asbo'},
    [23] = {vehicle = 'brioso2', label = 'Brioso 300'},
    [24] = {vehicle = 'caracara2', label = 'Caracara 4x4'},
    [25] = {vehicle = 'cheburek', label = 'Cheburek'},
    [26] = {vehicle = 'freecrawler', label = 'Freecrawler'},
    [27] = {vehicle = 'hellion', label = 'Hellion'},
    [28] = {vehicle = 'hermes', label = 'Hermes'},
    [29] = {vehicle = 'ingot', label = 'Ingot'},
    [30] = {vehicle = 'landstalker2', label = 'Landstalker XL'},
    [31] = {vehicle = 'manana', label = 'Manana'},
    [32] = {vehicle = 'mesa', label = 'Mesa'},
    [33] = {vehicle = 'minivan', label = 'Minivan'},
    [34] = {vehicle = 'peyote', label = 'Peyote'},
    [35] = {vehicle = 'primo', label = 'Primo'},
    [36] = {vehicle = 'rancherxl', label = 'Rancher XL'},
    [37] = {vehicle = 'sadler', label = 'Sadler'},
    [38] = {vehicle = 'stanier', label = 'Stanier'},
    [39] = {vehicle = 'stratum', label = 'Stratum'},
    [40] = {vehicle = 'tornado', label = 'Tornado'},
  },
  -- C CLASS
  [2] = {
    -- D
    [1] = {vehicle = 'asea', label = 'Asea'},
    [2] = {vehicle = 'bifta', label = 'Bifta'},
    [3] = {vehicle = 'bison', label = 'Bison'},
    [4] = {vehicle = 'blista', label = 'Blista'},
    [5] = {vehicle = 'btype', label = 'Roosevelt'},
    [6] = {vehicle = 'burrito3', label = 'Burrito'},
    [7] = {vehicle = 'emperor', label = 'Emperor'},
    [8] = {vehicle = 'fagaloa', label = 'Fagaloa'},
    [9] = {vehicle = 'glendale', label = 'Glendale'},
    [10] = {vehicle = 'issi3', label = 'Issi Classic'},
    [11] = {vehicle = 'landstalker', label = 'Landstalker'},
    [12] = {vehicle = 'panto', label = 'Panto'},
    [13] = {vehicle = 'patriot', label = 'Patriot'},
    [14] = {vehicle = 'pigalle', label = 'Pigalle'},
    [15] = {vehicle = 'radi', label = 'Radius'},
    [16] = {vehicle = 'regina', label = 'Regina'},
    [17] = {vehicle = 'rhapsody', label = 'Rhapsody'},
    [18] = {vehicle = 'stalion', label = 'Stallion'},
    [19] = {vehicle = 'surge', label = 'Surge'},
    [20] = {vehicle = 'voodoo', label = 'Voodoo'},
    [21] = {vehicle = 'washington', label = 'Washington'},
    [22] = {vehicle = 'asbo', label = 'Asbo'},
    [23] = {vehicle = 'brioso2', label = 'Brioso 300'},
    [24] = {vehicle = 'caracara2', label = 'Caracara 4x4'},
    [25] = {vehicle = 'cheburek', label = 'Cheburek'},
    [26] = {vehicle = 'freecrawler', label = 'Freecrawler'},
    [27] = {vehicle = 'hellion', label = 'Hellion'},
    [28] = {vehicle = 'hermes', label = 'Hermes'},
    [29] = {vehicle = 'ingot', label = 'Ingot'},
    [30] = {vehicle = 'landstalker2', label = 'Landstalker XL'},
    [31] = {vehicle = 'manana', label = 'Manana'},
    [32] = {vehicle = 'mesa', label = 'Mesa'},
    [33] = {vehicle = 'minivan', label = 'Minivan'},
    [34] = {vehicle = 'peyote', label = 'Peyote'},
    [35] = {vehicle = 'primo', label = 'Primo'},
    [36] = {vehicle = 'rancherxl', label = 'Rancher XL'},
    [37] = {vehicle = 'sadler', label = 'Sadler'},
    [38] = {vehicle = 'stanier', label = 'Stanier'},
    [39] = {vehicle = 'stratum', label = 'Stratum'},
    [40] = {vehicle = 'tornado', label = 'Tornado'},
    -- C
    [41] = {vehicle = 'baller2', label = 'Baller'},
    [42] = {vehicle = 'blade', label = 'Blade'},
    [43] = {vehicle = 'brawler', label = 'Brawler'},
    [44] = {vehicle = 'brioso', label = 'Brioso R/A'},
    [45] = {vehicle = 'buccaneer', label = 'Buccaneer'},
    [46] = {vehicle = 'casco', label = 'Casco'},
    [47] = {vehicle = 'cavalcade2', label = 'Cavalcade'},
    [48] = {vehicle = 'cavalcade2', label = 'Cavalcade'},
    [49] = {vehicle = 'chino', label = 'Chino'},
    [50] = {vehicle = 'coquette3', label = 'Coquette BlackFin'},
    [51] = {vehicle = 'dukes', label = 'Dukes'},
    [52] = {vehicle = 'faction', label = 'Faction'},
    [53] = {vehicle = 'fq2', label = 'FQ2'},
    [54] = {vehicle = 'gauntlet', label = 'Gauntlet'},
    [55] = {vehicle = 'issi2', label = 'Issi'},
    [56] = {vehicle = 'nightshade', label = 'Nightshade'},
    [57] = {vehicle = 'phoenix', label = 'Phoenix'},
    [58] = {vehicle = 'picador', label = 'Picador'},
    [59] = {vehicle = 'tampa', label = 'Tampa'},
    [60] = {vehicle = 'vigero', label = 'Vigero'},
    [61] = {vehicle = 'yosemite', label = 'Yosemite'},
    [62] = {vehicle = 'deviant', label = 'Deviant'},
    [63] = {vehicle = 'jb700', label = 'JB 700'},
    [64] = {vehicle = 'nebula', label = 'Nebula'},
    [65] = {vehicle = 'ruiner', label = 'Ruiner'},
  },
  -- B CLASS
  [3] =  {
    -- D
    [1] = {vehicle = 'asea', label = 'Asea'},
    [2] = {vehicle = 'bifta', label = 'Bifta'},
    [3] = {vehicle = 'bison', label = 'Bison'},
    [4] = {vehicle = 'blista', label = 'Blista'},
    [5] = {vehicle = 'btype', label = 'Roosevelt'},
    [6] = {vehicle = 'burrito3', label = 'Burrito'},
    [7] = {vehicle = 'emperor', label = 'Emperor'},
    [8] = {vehicle = 'fagaloa', label = 'Fagaloa'},
    [9] = {vehicle = 'glendale', label = 'Glendale'},
    [10] = {vehicle = 'issi3', label = 'Issi Classic'},
    [11] = {vehicle = 'landstalker', label = 'Landstalker'},
    [12] = {vehicle = 'panto', label = 'Panto'},
    [13] = {vehicle = 'patriot', label = 'Patriot'},
    [14] = {vehicle = 'pigalle', label = 'Pigalle'},
    [15] = {vehicle = 'radi', label = 'Radius'},
    [16] = {vehicle = 'regina', label = 'Regina'},
    [17] = {vehicle = 'rhapsody', label = 'Rhapsody'},
    [18] = {vehicle = 'stalion', label = 'Stallion'},
    [19] = {vehicle = 'surge', label = 'Surge'},
    [20] = {vehicle = 'voodoo', label = 'Voodoo'},
    [21] = {vehicle = 'washington', label = 'Washington'},
    [22] = {vehicle = 'asbo', label = 'Asbo'},
    [23] = {vehicle = 'brioso2', label = 'Brioso 300'},
    [24] = {vehicle = 'caracara2', label = 'Caracara 4x4'},
    [25] = {vehicle = 'cheburek', label = 'Cheburek'},
    [26] = {vehicle = 'freecrawler', label = 'Freecrawler'},
    [27] = {vehicle = 'hellion', label = 'Hellion'},
    [28] = {vehicle = 'hermes', label = 'Hermes'},
    [29] = {vehicle = 'ingot', label = 'Ingot'},
    [30] = {vehicle = 'landstalker2', label = 'Landstalker XL'},
    [31] = {vehicle = 'manana', label = 'Manana'},
    [32] = {vehicle = 'mesa', label = 'Mesa'},
    [33] = {vehicle = 'minivan', label = 'Minivan'},
    [34] = {vehicle = 'peyote', label = 'Peyote'},
    [35] = {vehicle = 'primo', label = 'Primo'},
    [36] = {vehicle = 'rancherxl', label = 'Rancher XL'},
    [37] = {vehicle = 'sadler', label = 'Sadler'},
    [38] = {vehicle = 'stanier', label = 'Stanier'},
    [39] = {vehicle = 'stratum', label = 'Stratum'},
    [40] = {vehicle = 'tornado', label = 'Tornado'},
    -- C
    [41] = {vehicle = 'baller2', label = 'Baller'},
    [42] = {vehicle = 'blade', label = 'Blade'},
    [43] = {vehicle = 'brawler', label = 'Brawler'},
    [44] = {vehicle = 'brioso', label = 'Brioso R/A'},
    [45] = {vehicle = 'buccaneer', label = 'Buccaneer'},
    [46] = {vehicle = 'casco', label = 'Casco'},
    [47] = {vehicle = 'cavalcade2', label = 'Cavalcade'},
    [48] = {vehicle = 'cavalcade2', label = 'Cavalcade'},
    [49] = {vehicle = 'chino', label = 'Chino'},
    [50] = {vehicle = 'coquette3', label = 'Coquette BlackFin'},
    [51] = {vehicle = 'dukes', label = 'Dukes'},
    [52] = {vehicle = 'faction', label = 'Faction'},
    [53] = {vehicle = 'fq2', label = 'FQ2'},
    [54] = {vehicle = 'gauntlet', label = 'Gauntlet'},
    [55] = {vehicle = 'issi2', label = 'Issi'},
    [56] = {vehicle = 'nightshade', label = 'Nightshade'},
    [57] = {vehicle = 'phoenix', label = 'Phoenix'},
    [58] = {vehicle = 'picador', label = 'Picador'},
    [59] = {vehicle = 'tampa', label = 'Tampa'},
    [60] = {vehicle = 'vigero', label = 'Vigero'},
    [61] = {vehicle = 'yosemite', label = 'Yosemite'},
    [62] = {vehicle = 'deviant', label = 'Deviant'},
    [63] = {vehicle = 'jb700', label = 'JB 700'},
    [64] = {vehicle = 'nebula', label = 'Nebula'},
    [65] = {vehicle = 'ruiner', label = 'Ruiner'},
    -- B
    [66] = {vehicle = 'alpha', label = 'Alpha'},
    [67] = {vehicle = 'baller3', label = 'Baller LE'},
    [68] = {vehicle = 'buffalo', label = 'Buffalo'},
    [69] = {vehicle = 'cognoscenti', label = 'Cognoscenti'},
    [70] = {vehicle = 'dominator', label = 'Dominator'},
    [71] = {vehicle = 'ellie', label = 'Ellie'},
    [72] = {vehicle = 'exemplar', label = 'Exemplar'},
    [73] = {vehicle = 'f620', label = 'F620'},
    [74] = {vehicle = 'felon', label = 'Felon'},
    [75] = {vehicle = 'felon2', label = 'Felon GT'},
    [76] = {vehicle = 'fugitive', label = 'Fugitive'},
    [77] = {vehicle = 'huntley', label = 'Huntley'},
    [78] = {vehicle = 'intruder', label = 'Intruder'},
    [79] = {vehicle = 'jackal', label = 'Jackal'},
    [80] = {vehicle = 'oracle', label = 'Oracle'},
    [81] = {vehicle = 'oracle2', label = 'Oracle XS'},
    [82] = {vehicle = 'rocoto', label = 'Rocoto'},
    [83] = {vehicle = 'sabregt', label = 'Sabre Turbo'},
    [84] = {vehicle = 'schafter2', label = 'Schafter'},
    [85] = {vehicle = 'sentinel2', label = 'Sentinel XS'},
    [86] = {vehicle = 'sentinel3', label = 'Sentinel Classic'},
    [87] = {vehicle = 'stingergt', label = 'Stinger GT'},
    [88] = {vehicle = 'superd', label = 'Super Diamond'},
    [89] = {vehicle = 'tailgater', label = 'Tailgater'},
    [90] = {vehicle = 'club', label = 'Club'},
    [91] = {vehicle = 'cog55', label = 'Cognoscenti 55'},
    [92] = {vehicle = 'vstr', label = 'V-STR'},
  },
  -- A CLASS
  [4] = {
    -- D
    [1] = {vehicle = 'asea', label = 'Asea'},
    [2] = {vehicle = 'bifta', label = 'Bifta'},
    [3] = {vehicle = 'bison', label = 'Bison'},
    [4] = {vehicle = 'blista', label = 'Blista'},
    [5] = {vehicle = 'btype', label = 'Roosevelt'},
    [6] = {vehicle = 'burrito3', label = 'Burrito'},
    [7] = {vehicle = 'emperor', label = 'Emperor'},
    [8] = {vehicle = 'fagaloa', label = 'Fagaloa'},
    [9] = {vehicle = 'glendale', label = 'Glendale'},
    [10] = {vehicle = 'issi3', label = 'Issi Classic'},
    [11] = {vehicle = 'landstalker', label = 'Landstalker'},
    [12] = {vehicle = 'panto', label = 'Panto'},
    [13] = {vehicle = 'patriot', label = 'Patriot'},
    [14] = {vehicle = 'pigalle', label = 'Pigalle'},
    [15] = {vehicle = 'radi', label = 'Radius'},
    [16] = {vehicle = 'regina', label = 'Regina'},
    [17] = {vehicle = 'rhapsody', label = 'Rhapsody'},
    [18] = {vehicle = 'stalion', label = 'Stallion'},
    [19] = {vehicle = 'surge', label = 'Surge'},
    [20] = {vehicle = 'voodoo', label = 'Voodoo'},
    [21] = {vehicle = 'washington', label = 'Washington'},
    [22] = {vehicle = 'asbo', label = 'Asbo'},
    [23] = {vehicle = 'brioso2', label = 'Brioso 300'},
    [24] = {vehicle = 'caracara2', label = 'Caracara 4x4'},
    [25] = {vehicle = 'cheburek', label = 'Cheburek'},
    [26] = {vehicle = 'freecrawler', label = 'Freecrawler'},
    [27] = {vehicle = 'hellion', label = 'Hellion'},
    [28] = {vehicle = 'hermes', label = 'Hermes'},
    [29] = {vehicle = 'ingot', label = 'Ingot'},
    [30] = {vehicle = 'landstalker2', label = 'Landstalker XL'},
    [31] = {vehicle = 'manana', label = 'Manana'},
    [32] = {vehicle = 'mesa', label = 'Mesa'},
    [33] = {vehicle = 'minivan', label = 'Minivan'},
    [34] = {vehicle = 'peyote', label = 'Peyote'},
    [35] = {vehicle = 'primo', label = 'Primo'},
    [36] = {vehicle = 'rancherxl', label = 'Rancher XL'},
    [37] = {vehicle = 'sadler', label = 'Sadler'},
    [38] = {vehicle = 'stanier', label = 'Stanier'},
    [39] = {vehicle = 'stratum', label = 'Stratum'},
    [40] = {vehicle = 'tornado', label = 'Tornado'},
    -- C
    [41] = {vehicle = 'baller2', label = 'Baller'},
    [42] = {vehicle = 'blade', label = 'Blade'},
    [43] = {vehicle = 'brawler', label = 'Brawler'},
    [44] = {vehicle = 'brioso', label = 'Brioso R/A'},
    [45] = {vehicle = 'buccaneer', label = 'Buccaneer'},
    [46] = {vehicle = 'casco', label = 'Casco'},
    [47] = {vehicle = 'cavalcade2', label = 'Cavalcade'},
    [48] = {vehicle = 'cavalcade2', label = 'Cavalcade'},
    [49] = {vehicle = 'chino', label = 'Chino'},
    [50] = {vehicle = 'coquette3', label = 'Coquette BlackFin'},
    [51] = {vehicle = 'dukes', label = 'Dukes'},
    [52] = {vehicle = 'faction', label = 'Faction'},
    [53] = {vehicle = 'fq2', label = 'FQ2'},
    [54] = {vehicle = 'gauntlet', label = 'Gauntlet'},
    [55] = {vehicle = 'issi2', label = 'Issi'},
    [56] = {vehicle = 'nightshade', label = 'Nightshade'},
    [57] = {vehicle = 'phoenix', label = 'Phoenix'},
    [58] = {vehicle = 'picador', label = 'Picador'},
    [59] = {vehicle = 'tampa', label = 'Tampa'},
    [60] = {vehicle = 'vigero', label = 'Vigero'},
    [61] = {vehicle = 'yosemite', label = 'Yosemite'},
    [62] = {vehicle = 'deviant', label = 'Deviant'},
    [63] = {vehicle = 'jb700', label = 'JB 700'},
    [64] = {vehicle = 'nebula', label = 'Nebula'},
    [65] = {vehicle = 'ruiner', label = 'Ruiner'},
    -- B
    [66] = {vehicle = 'alpha', label = 'Alpha'},
    [67] = {vehicle = 'baller3', label = 'Baller LE'},
    [68] = {vehicle = 'buffalo', label = 'Buffalo'},
    [69] = {vehicle = 'cognoscenti', label = 'Cognoscenti'},
    [70] = {vehicle = 'dominator', label = 'Dominator'},
    [71] = {vehicle = 'ellie', label = 'Ellie'},
    [72] = {vehicle = 'exemplar', label = 'Exemplar'},
    [73] = {vehicle = 'f620', label = 'F620'},
    [74] = {vehicle = 'felon', label = 'Felon'},
    [75] = {vehicle = 'felon2', label = 'Felon GT'},
    [76] = {vehicle = 'fugitive', label = 'Fugitive'},
    [77] = {vehicle = 'huntley', label = 'Huntley'},
    [78] = {vehicle = 'intruder', label = 'Intruder'},
    [79] = {vehicle = 'jackal', label = 'Jackal'},
    [80] = {vehicle = 'oracle', label = 'Oracle'},
    [81] = {vehicle = 'oracle2', label = 'Oracle XS'},
    [82] = {vehicle = 'rocoto', label = 'Rocoto'},
    [83] = {vehicle = 'sabregt', label = 'Sabre Turbo'},
    [84] = {vehicle = 'schafter2', label = 'Schafter'},
    [85] = {vehicle = 'sentinel2', label = 'Sentinel XS'},
    [86] = {vehicle = 'sentinel3', label = 'Sentinel Classic'},
    [87] = {vehicle = 'stingergt', label = 'Stinger GT'},
    [88] = {vehicle = 'superd', label = 'Super Diamond'},
    [89] = {vehicle = 'tailgater', label = 'Tailgater'},
    [90] = {vehicle = 'club', label = 'Club'},
    [91] = {vehicle = 'cog55', label = 'Cognoscenti 55'},
    [92] = {vehicle = 'vstr', label = 'V-STR'},
    -- A
    [93] = {vehicle = 'ardent', label = 'Ardent'},
    [94] = {vehicle = 'banshee', label = 'Banshee'},
    [95] = {vehicle = 'bestiagts', label = 'Bestia GTS'},
    [96] = {vehicle = 'buffalo2', label = 'Buffalo S'},
    [97] = {vehicle = 'bullet', label = 'Bullet'},
    [98] = {vehicle = 'carbonizzare', label = 'Carbonizzare'},
    [99] = {vehicle = 'cheetah2', label = 'Cheetah Classic'},
    [100] = {vehicle = 'cogcabrio', label = 'Cogniscenti Cabrio'},
    [101] = {vehicle = 'comet2', label = 'Comet'},
    [102] = {vehicle = 'coquette', label = 'Coquette'},
    [103] = {vehicle = 'coquette2', label = 'Coquette Classic'},
    [104] = {vehicle = 'elegy', label = 'Elegy'},
    [105] = {vehicle = 'elegy2', label = 'Elegy RH8'},
    [106] = {vehicle = 'felon2', label = 'Felon GT'},
    [107] = {vehicle = 'feltzer2', label = 'Feltzer'},
    [108] = {vehicle = 'flashgt', label = 'Flash GT'},
    [109] = {vehicle = 'futo', label = 'Futo'},
    [110] = {vehicle = 'infernus', label = 'Infernus'},
    [111] = {vehicle = 'infernus2', label = 'Infernus Classic'},
    [112] = {vehicle = 'jester', label = 'Jester'},
    [113] = {vehicle = 'jester3', label = 'Jester Classic'},
    [114] = {vehicle = 'kuruma', label = 'Kuruma'},
    [115] = {vehicle = 'mamba', label = 'Mamba'},
    [116] = {vehicle = 'neon', label = 'Neon'},
    [117] = {vehicle = 'ninef', label = '9F'},
    [118] = {vehicle = 'ninef2', label = '9F Cabrio'},
    [119] = {vehicle = 'rapidgt', label = 'Rapid GT'},
    [120] = {vehicle = 'rapidgt3', label = 'Rapid GT Classic'},
    [121] = {vehicle = 'schafter3', label = 'Schafter V12'},
    [122] = {vehicle = 'sentinel', label = 'Sentinel'},
    [123] = {vehicle = 'specter', label = 'Specter'},
    [124] = {vehicle = 'sultan', label = 'Sultan'},
    [125] = {vehicle = 'sultanrs', label = 'Sultan RS'},
  },
  -- S CLASS
  [5] = {
    -- D
    [1] = {vehicle = 'asea', label = 'Asea'},
    [2] = {vehicle = 'bifta', label = 'Bifta'},
    [3] = {vehicle = 'bison', label = 'Bison'},
    [4] = {vehicle = 'blista', label = 'Blista'},
    [5] = {vehicle = 'btype', label = 'Roosevelt'},
    [6] = {vehicle = 'burrito3', label = 'Burrito'},
    [7] = {vehicle = 'emperor', label = 'Emperor'},
    [8] = {vehicle = 'fagaloa', label = 'Fagaloa'},
    [9] = {vehicle = 'glendale', label = 'Glendale'},
    [10] = {vehicle = 'issi3', label = 'Issi Classic'},
    [11] = {vehicle = 'landstalker', label = 'Landstalker'},
    [12] = {vehicle = 'panto', label = 'Panto'},
    [13] = {vehicle = 'patriot', label = 'Patriot'},
    [14] = {vehicle = 'pigalle', label = 'Pigalle'},
    [15] = {vehicle = 'radi', label = 'Radius'},
    [16] = {vehicle = 'regina', label = 'Regina'},
    [17] = {vehicle = 'rhapsody', label = 'Rhapsody'},
    [18] = {vehicle = 'stalion', label = 'Stallion'},
    [19] = {vehicle = 'surge', label = 'Surge'},
    [20] = {vehicle = 'voodoo', label = 'Voodoo'},
    [21] = {vehicle = 'washington', label = 'Washington'},
    [22] = {vehicle = 'asbo', label = 'Asbo'},
    [23] = {vehicle = 'brioso2', label = 'Brioso 300'},
    [24] = {vehicle = 'caracara2', label = 'Caracara 4x4'},
    [25] = {vehicle = 'cheburek', label = 'Cheburek'},
    [26] = {vehicle = 'freecrawler', label = 'Freecrawler'},
    [27] = {vehicle = 'hellion', label = 'Hellion'},
    [28] = {vehicle = 'hermes', label = 'Hermes'},
    [29] = {vehicle = 'ingot', label = 'Ingot'},
    [30] = {vehicle = 'landstalker2', label = 'Landstalker XL'},
    [31] = {vehicle = 'manana', label = 'Manana'},
    [32] = {vehicle = 'mesa', label = 'Mesa'},
    [33] = {vehicle = 'minivan', label = 'Minivan'},
    [34] = {vehicle = 'peyote', label = 'Peyote'},
    [35] = {vehicle = 'primo', label = 'Primo'},
    [36] = {vehicle = 'rancherxl', label = 'Rancher XL'},
    [37] = {vehicle = 'sadler', label = 'Sadler'},
    [38] = {vehicle = 'stanier', label = 'Stanier'},
    [39] = {vehicle = 'stratum', label = 'Stratum'},
    [40] = {vehicle = 'tornado', label = 'Tornado'},
    -- C
    [41] = {vehicle = 'baller2', label = 'Baller'},
    [42] = {vehicle = 'blade', label = 'Blade'},
    [43] = {vehicle = 'brawler', label = 'Brawler'},
    [44] = {vehicle = 'brioso', label = 'Brioso R/A'},
    [45] = {vehicle = 'buccaneer', label = 'Buccaneer'},
    [46] = {vehicle = 'casco', label = 'Casco'},
    [47] = {vehicle = 'cavalcade2', label = 'Cavalcade'},
    [48] = {vehicle = 'cavalcade2', label = 'Cavalcade'},
    [49] = {vehicle = 'chino', label = 'Chino'},
    [50] = {vehicle = 'coquette3', label = 'Coquette BlackFin'},
    [51] = {vehicle = 'dukes', label = 'Dukes'},
    [52] = {vehicle = 'faction', label = 'Faction'},
    [53] = {vehicle = 'fq2', label = 'FQ2'},
    [54] = {vehicle = 'gauntlet', label = 'Gauntlet'},
    [55] = {vehicle = 'issi2', label = 'Issi'},
    [56] = {vehicle = 'nightshade', label = 'Nightshade'},
    [57] = {vehicle = 'phoenix', label = 'Phoenix'},
    [58] = {vehicle = 'picador', label = 'Picador'},
    [59] = {vehicle = 'tampa', label = 'Tampa'},
    [60] = {vehicle = 'vigero', label = 'Vigero'},
    [61] = {vehicle = 'yosemite', label = 'Yosemite'},
    [62] = {vehicle = 'deviant', label = 'Deviant'},
    [63] = {vehicle = 'jb700', label = 'JB 700'},
    [64] = {vehicle = 'nebula', label = 'Nebula'},
    [65] = {vehicle = 'ruiner', label = 'Ruiner'},
    -- B
    [66] = {vehicle = 'alpha', label = 'Alpha'},
    [67] = {vehicle = 'baller3', label = 'Baller LE'},
    [68] = {vehicle = 'buffalo', label = 'Buffalo'},
    [69] = {vehicle = 'cognoscenti', label = 'Cognoscenti'},
    [70] = {vehicle = 'dominator', label = 'Dominator'},
    [71] = {vehicle = 'ellie', label = 'Ellie'},
    [72] = {vehicle = 'exemplar', label = 'Exemplar'},
    [73] = {vehicle = 'f620', label = 'F620'},
    [74] = {vehicle = 'felon', label = 'Felon'},
    [75] = {vehicle = 'felon2', label = 'Felon GT'},
    [76] = {vehicle = 'fugitive', label = 'Fugitive'},
    [77] = {vehicle = 'huntley', label = 'Huntley'},
    [78] = {vehicle = 'intruder', label = 'Intruder'},
    [79] = {vehicle = 'jackal', label = 'Jackal'},
    [80] = {vehicle = 'oracle', label = 'Oracle'},
    [81] = {vehicle = 'oracle2', label = 'Oracle XS'},
    [82] = {vehicle = 'rocoto', label = 'Rocoto'},
    [83] = {vehicle = 'sabregt', label = 'Sabre Turbo'},
    [84] = {vehicle = 'schafter2', label = 'Schafter'},
    [85] = {vehicle = 'sentinel2', label = 'Sentinel XS'},
    [86] = {vehicle = 'sentinel3', label = 'Sentinel Classic'},
    [87] = {vehicle = 'stingergt', label = 'Stinger GT'},
    [88] = {vehicle = 'superd', label = 'Super Diamond'},
    [89] = {vehicle = 'tailgater', label = 'Tailgater'},
    [90] = {vehicle = 'club', label = 'Club'},
    [91] = {vehicle = 'cog55', label = 'Cognoscenti 55'},
    [92] = {vehicle = 'vstr', label = 'V-STR'},
    -- A
    [93] = {vehicle = 'ardent', label = 'Ardent'},
    [94] = {vehicle = 'banshee', label = 'Banshee'},
    [95] = {vehicle = 'bestiagts', label = 'Bestia GTS'},
    [96] = {vehicle = 'buffalo2', label = 'Buffalo S'},
    [97] = {vehicle = 'bullet', label = 'Bullet'},
    [98] = {vehicle = 'carbonizzare', label = 'Carbonizzare'},
    [99] = {vehicle = 'cheetah2', label = 'Cheetah Classic'},
    [100] = {vehicle = 'cogcabrio', label = 'Cogniscenti Cabrio'},
    [101] = {vehicle = 'comet2', label = 'Comet'},
    [102] = {vehicle = 'coquette', label = 'Coquette'},
    [103] = {vehicle = 'coquette2', label = 'Coquette Classic'},
    [104] = {vehicle = 'elegy', label = 'Elegy'},
    [105] = {vehicle = 'elegy2', label = 'Elegy RH8'},
    [106] = {vehicle = 'felon2', label = 'Felon GT'},
    [107] = {vehicle = 'feltzer2', label = 'Feltzer'},
    [108] = {vehicle = 'flashgt', label = 'Flash GT'},
    [109] = {vehicle = 'futo', label = 'Futo'},
    [110] = {vehicle = 'infernus', label = 'Infernus'},
    [111] = {vehicle = 'infernus2', label = 'Infernus Classic'},
    [112] = {vehicle = 'jester', label = 'Jester'},
    [113] = {vehicle = 'jester3', label = 'Jester Classic'},
    [114] = {vehicle = 'kuruma', label = 'Kuruma'},
    [115] = {vehicle = 'mamba', label = 'Mamba'},
    [116] = {vehicle = 'neon', label = 'Neon'},
    [117] = {vehicle = 'ninef', label = '9F'},
    [118] = {vehicle = 'ninef2', label = '9F Cabrio'},
    [119] = {vehicle = 'rapidgt', label = 'Rapid GT'},
    [120] = {vehicle = 'rapidgt3', label = 'Rapid GT Classic'},
    [121] = {vehicle = 'schafter3', label = 'Schafter V12'},
    [122] = {vehicle = 'sentinel', label = 'Sentinel'},
    [123] = {vehicle = 'specter', label = 'Specter'},
    [124] = {vehicle = 'sultan', label = 'Sultan'},
    [125] = {vehicle = 'sultanrs', label = 'Sultan RS'},
    -- S
    [126] = {vehicle = 'thrax', label = 'Thrax'},
    [127] = {vehicle = 'neo', label = 'Neo'},
    [128] = {vehicle = 'adder', label = 'Adder'},
    [129] = {vehicle = 'banshee2', label = 'Banshee 900R'},
    [130] = {vehicle = 'comet5', label = 'Comet SR'},
    [131] = {vehicle = 'gp1', label = 'GP1'},
    [132] = {vehicle = 'lynx', label = 'Lynx'},
    [133] = {vehicle = 'massacro', label = 'Massacro'},
    -- S Addons
    [134] = {vehicle = 'gtr', label = 'GTR R35'},
  }
}

Config.VehicleCoords = {
  [1] = vector4(-500.81, 427.35, 96.64, 133.0),
  [2] = vector4(-769.63, 672.36, 144.55, 213.79),
  [3] = vector4(112.79, 499.74, 146.81, 10.97),
  [4] = vector4(-179.79, 582.94, 197.29, 359.89),
  [5] = vector4(-274.02, 598.66, 181.35, 176.77),
  [6] = vector4(-343.05, 633.71, 171.98, 53.43),
  [7] = vector4(-594.22, 753.58, 183.38, 259.38),
  [8] = vector4(-916.52, 807.3, 184.02, 4.11),
  [9] = vector4(-991.45, 826.99, 172.1, 224.73),
  [10] = vector4(-1244.79, 669.2, 142.49, 136.76),
  [11] = vector4(-1499.15, 416.83, 110.77, 224.67),
  [12] = vector4(-1177.59, 458.31, 86.35, 85.75),
  [13] = vector4(-1108.26, 490.79, 81.86, 350.03),
  [14] = vector4(-1044.83, 500.57, 83.74, 219.88),
  [15] = vector4(-1198.29, 321.58, 70.44, 195.11),
  [16] = vector4(-1183.92, 326.19, 70.26, 17.77),
  [17] = vector4(-1061.59, 302.42, 65.61, 352.77),
  [18] = vector4(-1615.95, 15.92, 61.84, 333.89),
  [19] = vector4(-1504.35, 22.82, 55.92, 178.51),
  [20] = vector4(-1405.34, 67.33, 52.65, 236.7),
  [21] = vector4(-1270.39, -251.43, 46.71, 37.96),
  [22] = vector4(-1307.19, -218.86, 46.71, 127.15),
  [23] = vector4(-1306.15, -193.62, 51.21, 33.23),
  [24] = vector4(-1299.96, -228.39, 55.77, 307.2),
  [25] = vector4(-1547.79, -424.39, 41.65, 230.51),
  [26] = vector4(-1545.86, -398.66, 41.65, 228.34),
  [27] = vector4(-1524.21, -421.62, 35.1, 47.93),
  [28] = vector4(-1702.51, -447.81, 41.28, 318.61),
  [29] = vector4(-1664.58, -386.75, 44.5, 49.21),
  [30] = vector4(-1441.49, -685.05, 25.97, 211.66),
  [31] = vector4(-1341.97, -896.32, 13.09, 307.34),
  [32] = vector4(-1318.9, -1148.32, 4.16, 269.93),
  [33] = vector4(-1260.65, -1241.45, 5.09, 109.52),
  [34] = vector4(-1278.32, -1307.57, 3.69, 292.01),
  [35] = vector4(-1027.49, -1514.22, 5.25, 35.44),
  [36] = vector4(-981.54, -1477.71, 4.67, 126.01),
  [37] = vector4(-900.96, -1535.16, 4.68, 198.12),
  [38] = vector4(-813.74, -1274.51, 4.66, 349.25),
  [39] = vector4(-1048.05, -1152.32, 1.82, 213.2),
  [40] = vector4(-875.37, 48.05, 48.42, 14.09),
  [41] = vector4(-907.09, 191.83, 69.11, 125.25),
  [42] = vector4(-925.3, 211.22, 67.12, 331.63),
  [43] = vector4(-588.47, 184.9, 70.72, 269.89),
  [44] = vector4(-503.4, 58.06, 56.15, 264.55),
  [45] = vector4(-467.55, 74.42, 58.32, 314.07),
  [46] = vector4(-468.08, 195.17, 74.9, 358.66),
  [47] = vector4(-380.62, 181.38, 79.67, 182.5),
  [48] = vector4(-141.02, -30.8, 57.69, 161.52),
  [49] = vector4(-36.62, -27.82, 68.66, 250.59),
  [50] = vector4(-0.99, -54.98, 62.94, 244.3),
  [51] = vector4(128.09, -78.35, 63.98, 277.74),
  [52] = vector4(161.5, -113.64, 61.95, 250.05),
  [53] = vector4(250.57, 31.76, 83.46, 253.26),
}

Config.ClassPrices = {
  ['S'] = 125,
  ['A'] = 90,
  ['B'] = 65,
  ['C'] = 42,
  ['D'] = 20,
}

Config.DropOffPoints = {
  [1] = vector3(33.42, -1032.72, 28.84),
  [2] = vector3(1130.11, -1302.56, 34.09),
  [3] = vector3(1125.74, -1404.87, 34.54),
  [4] = vector3(989.24, -2395.52, 30.55),
  [5] = vector3(804.07, -2222.52, 29.36),
  [6] = vector3(873.58, -2197.69, 30.52),
  [7] = vector3(-1477.43, -3285.84, 14.0),
  [8] = vector3(-1151.67, -1566.02, 4.35),
  [9] = vector3(-1990.05, -321.07, 43.96),
  [10] = vector3(496.36, -567.95, 24.66),
}

Config.VinPoints = {
  [1] = {
    ['coords'] = vector3(-1160.11, -2018.22, 13.18),
    ['shape'] = {
      vector2(-1159.95, -2011.13),
      vector2(-1166.89, -2018.19),
      vector2(-1157.44, -2026.31),
      vector2(-1151.19, -2019.14),
    },
    ['minZ'] = 12.18,
    ['maxZ'] = 15.18
  },
  [2] = {
    ['coords'] = vector3(-327.37, -136.92, 39.01),
    ['shape'] = {
      vector2(-332.54, -139.05),
      vector2(-322.68, -142.36),
      vector2(-319.26, -131.25),
      vector2(-328.74, -127.76),
    },
    ['minZ'] = 38.01,
    ['maxZ'] = 41.01
  },
}